---
title: "R Notebook"
output: html_notebook
---

```{r}
#Load libraries
library(dplyr)
library(ggplot2)
library(nycflights13)
library(resampledata3)
library(tidyverse)
```

```{r}
glimpse(flights)
```
```{r}
united_flights <- flights %>%
  filter(carrier == "UA")%>%
  filter(!is.na(dep_delay)) %>%
  filter(!is.na(arr_delay)) %>%
  filter(!is.na(air_time)) %>%
  mutate(gain = dep_delay - arr_delay)
glimpse(united_flights)
```

```{r}
late <- united_flights %>%
  filter(dep_delay >0) %>%
  filter(!is.na(dep_delay))
glimpse(late)
```

```{r}
very_late <- united_flights %>%
  filter(dep_delay >30) %>%
  filter(!is.na(dep_delay))
glimpse(very_late)
```

```{r}
united_flights <- united_flights %>%
  mutate(late = dep_delay >0) %>% 
  mutate(very_late = dep_delay >30)
glimpse(united_flights)
```

```{r}
summary(united_flights$gain)
```

```{r}
ggplot(data = united_flights, mapping = aes(x = gain)) +
  geom_histogram(bins=40, color="white", fill="steelblue")
```


```{r}
ggplot(data=united_flights, aes(x=late, y=gain))+
geom_boxplot(color="steelblue", fill="white")
```

```{r}
ggplot(data=united_flights, aes(x=very_late, y=gain))+
geom_boxplot(color="steelblue", fill="white")
```



### Late Hypothesis Test
### µ0 = µA
### µ0 != µA

```{r}
t.test(gain~late,united_flights, conf.level= 0.95)
```
```{r}
t.test(gain~very_late,united_flights, conf.level= 0.95)
```

